crm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignupView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    # Reset password
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(), name='reset_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path

from .views import LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, AssignAgentView
from .views import CategoryListView, CategoryDetailView, LeadCategoryUpdateView

app_name="leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='list'),
    path('create', LeadCreateView.as_view(), name='create'),
    path('<int:pk>', LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/update', LeadUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/assign', AssignAgentView.as_view(), name='assign'),

    path('categories', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>', CategoryDetailView.as_view(), name='category-detail'),

    path('<int:pk>/category', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
]

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser

class User(AbstractUser): # Need to specify custom User model in settings.py
    is_organisor = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)

class UserProfile(models.Model):
    user = models.OneToOneField("User", on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category", related_name="leads" ,on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    #email = models.EmailField()

    def __str__(self):
        return self.first_name

class Agent(models.Model):
    user = models.OneToOneField("User", on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=30)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

def post_user_created_signal(sender, instance, created, **kwargs):
    if created: # Created or Updated?
        UserProfile.objects.create(user = instance)

post_save.connect(post_user_created_signal, sender=User)

# Using the manager
# Lead.objects.create(first_name = 'A', last_name = 'B', age = 30)
# Lead.objects.all()
# Lead.objects.filter(first_name='A')
# Lead.objects.filter(age__gt= 20)
# Lead.objects.get(id=15)

leads/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Lead, Agent

User = get_user_model()

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
            'description',
            'phone_number'
        )

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisation=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields['agent'].queryset = agents
    
class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ("category",)

leads/views.py
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import OrganisorAndLoginRequiredMixin
from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from .models import Lead, Agent, Category
from .forms import LeadModelForm, CustomUserCreationForm, AssignAgentForm, LeadCategoryUpdateForm

class SignupView(CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")

# Class based views

# TemplateView: basic class based view class
class LandingPageView(TemplateView):
    template_name = "landing.html"

# CRUD
class LeadListView(LoginRequiredMixin, ListView):
    template_name = "leads/lead_list.html"
    
    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile, agent__isnull=False)
        else:
            queryset = Lead.objects.filter(organisation = user.agent.organisation, agent__isnull=False)
            queryset = queryset.filter(agent__user = user)
        return queryset # Django calls the database based on the filters

    def get_context_data(self, **kwargs):
        context = super(LeadListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(
                organisation = user.userprofile, 
                agent__isnull=True)
            context.update({
                "unassigned_leads": queryset
            })
        return context

class LeadDetailView(LoginRequiredMixin, DetailView):
    template_name = "leads/lead_detail.html"
    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation = user.agent.organisation)
            queryset = queryset.filter(agent__user = user)
        return queryset # Django calls the database based on the filters
    context_object_name = "lead"

class LeadCreateView(OrganisorAndLoginRequiredMixin, CreateView):
    template_name = "leads/lead_create.html"
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("leads:list")

    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organisation = self.request.user.userprofile
        lead.save()
        send_mail(
            subject="A lead has been created", 
            message="Goto the site to see the new lead", 
            from_email="test@test.com", 
            recipient_list=["test2@test.com"]
        )
        return super(LeadCreateView, self).form_valid(form)

class LeadUpdateView(OrganisorAndLoginRequiredMixin, UpdateView):
    template_name = "leads/lead_update.html"
    form_class = LeadModelForm
    
    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation = user.agent.organisation)
            queryset = queryset.filter(agent__user = user)
        return queryset # Django calls the database based on the filters

    def get_success_url(self):
        return reverse("leads:list")

class LeadDeleteView(OrganisorAndLoginRequiredMixin, DeleteView):
    template_name = "leads/lead_delete.html" # <- Template view

    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation = user.agent.organisation)
            queryset = queryset.filter(agent__user = user)
        return queryset # Django calls the database based on the filters
    
    def get_success_url(self):
        return reverse("leads:list")

class AssignAgentView(OrganisorAndLoginRequiredMixin, FormView):
    template_name = "leads/assign_agent.html"
    form_class = AssignAgentForm

    # Pass extra arguments to the form
    def get_form_kwargs(self,**kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update( {
            "request": self.request
        })
        return kwargs

    def form_valid(self, form):
        agent = form.cleaned_data['agent']
        lead = Lead.objects.get(id=self.kwargs['pk'])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)

    def get_success_url(self):
        return reverse("leads:list")

class CategoryListView(LoginRequiredMixin, ListView):
    template_name = "leads/category_list.html"
    context_object_name = "category_list"

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation = user.agent.organisation)

        context.update({
            "unassigned_lead_count": queryset.filter(category__isnull=True).count()
        })
        return context

    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Category.objects.filter(organisation = user.userprofile)
        else:
            queryset = Category.objects.filter(organisation = user.agent.organisation)
        return queryset

class CategoryDetailView(LoginRequiredMixin, DetailView):
    template_name = "leads/category_detail.html"
    context_object_name = "category"

    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Category.objects.filter(organisation = user.userprofile)
        else:
            queryset = Category.objects.filter(organisation = user.agent.organisation)
        return queryset

class LeadCategoryUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "leads/lead_category_update.html"
    form_class = LeadCategoryUpdateForm
    
    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation = user.agent.organisation)
            queryset = queryset.filter(agent__user = user)
        return queryset # Django calls the database based on the filters

    def get_success_url(self):
        return reverse("leads:detail", kwargs={"pk": self.get_object().id})

leads/templates/leads/assign_agent.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <h2 class="text-2xl text-gray-800">Assign an agent to this lead</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rouded-md" type="submit">Assign</button>
    </form>
    <div class="py-5 border-t border-gray-200 mt-5">
        <a class="hover:text-blue-500" href="{% url 'leads:list' %}">Go back to leads</a>
    </div>

</div>


{% endblock content %}

leads/templates/leads/category_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{ category.name }}</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">These are the leads under this category</p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">First name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Last name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Actions</th>
          </tr>
        </thead>
        <tbody>
            
        {% for lead in category.leads.all %}
          <tr>
            <td class="px-4 py-3">{{ lead.first_name }}</td>
            <td class="px-4 py-3">{{ lead.last_name }}</td>
            <td class="px-4 py-3">
                <a href="{% url 'leads:detail' lead.id %}" >Edit</a>
            </td>
          </tr>
        {% endfor %}
          
        </tbody>
      </table>
    </div>
    
  </div>
</section>

{% endblock content %}

leads/templates/leads/category_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">These categories segment the Leads</p>
    </div>
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Lead count</th>
          </tr>
        </thead>
        <tbody>
            <tr>
                <td class="px-4 py-3">Unassigned</td>
                <td class="px-4 py-3">{{ unassigned_lead_count }}</td>
            </tr>
        {% for category in category_list %}
          <tr>
            
            <td class="px-4 py-3"><a href="{% url 'leads:category-detail' category.pk %}">{{ category.name }}</a></td>
            <td class="px-4 py-3">0</td>
          </tr>
        {% endfor %}
          
        </tbody>
      </table>
    </div>
    
  </div>
</section>

{% endblock content %}

leads/templates/leads/lead_category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="bg-grey-light p-3 rounded font-sans w-full m-4">
  <ol class="list-reset flex text-grey-dark">
    <li><a href="{% url 'landing-page' %}" class="text-blue font-bold">Home</a></li>
    <li><span class="mx-2">/</span></li>
    <li><a href="{% url 'leads:list' %}" class="text-blue font-bold">Leads</a></li>
    <li><span class="mx-2">/</span></li>
    <li><a href="{% url 'leads:detail' lead.id %}" class="text-blue font-bold">{{ lead.first_name }}</a></li>
    <li><span class="mx-2">/</span></li>
    <li>Update</li>
  </ol>
</div>

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:detail' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
          <a href="{% url 'leads:lead-category-update' lead.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Category</a>
          <a href="{% url 'leads:update' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
        </div>

        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rouded-md" type="submit">Update</button>
        </form>
        
      </div>
      
    </div>
  </div>
</section>

{% endblock content %}

leads/templates/leads/lead_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}


<div class="max-w-lg mx-auto">
    <h2 class="text-2xl text-gray-800">Create lead</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rouded-md" type="submit">Create</button>
    </form>
    <div class="py-5 border-t border-gray-200 mt-5">
        <a class="hover:text-blue-500" href="{% url 'leads:list' %}">Go back to leads</a>
    </div>
</div>


{% endblock content %}

leads/templates/leads/lead_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <h2>Are you sure you want to delete this lead?</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="w-full text-white bg-red-500 hover:bg-red-600 px-3 py-1 rouded-md" type="submit">Delete</button>
    </form>
    <div class="py-5 border-t border-gray-200 mt-5">
        <a class="hover:text-blue-500" href="{% url 'leads:update' lead.id %}">Go back</a>
    </div>

</div>
{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}

{% block content %}

<div class="bg-grey-light p-3 rounded font-sans w-full m-4">
  <ol class="list-reset flex text-grey-dark">
    <li><a href="{% url 'landing-page' %}" class="text-blue font-bold">Home</a></li>
    <li><span class="mx-2">/</span></li>
    <li><a href="{% url 'leads:list' %}" class="text-blue font-bold">Leads</a></li>
    <li><span class="mx-2">/</span></li>
    <li>{{ lead.first_name }}</li>
  </ol>
</div>

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:detail' lead.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Details</a>
          <a href="{% url 'leads:lead-category-update' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
          <a href="{% url 'leads:update' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
        </div>
        <p class="leading-relaxed mb-4">{{ lead.description }}</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Full name</span>
          <span class="ml-auto text-gray-900">{{ lead.first_name }} {{ lead.last_name }}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{ lead.age }}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Date added</span>
          <span class="ml-auto text-gray-900">{{ lead.date_added }}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Phone number</span>
          <span class="ml-auto text-gray-900">{{ lead.phone_number }}</span>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

leads/templates/leads/lead_list.html
{% extends "base.html" %}

{% block content %}

<div class="bg-grey-light p-3 rounded font-sans w-full m-4">
  <ol class="list-reset flex text-grey-dark">
    <li><a href="{% url 'landing-page' %}" class="text-blue font-bold">Home</a></li>
    <li><span class="mx-2">/</span></li>
    <li>Leads</li>
  </ol>
</div>

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
            <h1 class="text-4xl text-gray-800">Leads</h1>
            <a href="{% url 'leads:category-list'  %}" class="mt-3 text-indigo-500 inline-flex items-center">View categories
            </a>
        </div>
        {% if request.user.is_organisor %}
        <div>
            <a href="{% url 'leads:create' %}" class="text-gray-500 hover:text-blue-500">Create new lead</a>
        </div>
        {% endif %}
    </div>

    <div class="flex flex-wrap w-full">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">First name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Last name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Date added</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Actions</th>
          </tr>
        </thead>
        <tbody>
        {% for lead in object_list %}
          <tr>
            <td class="px-4 py-3">{{ lead.first_name }}</td>
            <td class="px-4 py-3">{{ lead.last_name }}</td>
            <td class="px-4 py-3">{{ lead.date_added }}</td>
            <td class="px-4 py-3"><a href="{% url 'leads:detail' lead.id %}" class="mt-3 text-indigo-500 inline-flex items-center">View</a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>

    </div>

    {% if unassigned_leads.exists %}
      <div class="mt-5 flex flex-wrap -m-4">
        <div class="p-4 w-full">
          <h1 class="text-4xl text-gray-800">Unassigned leads</h1>
        </div>
        {% for lead in unassigned_leads %}

        <div class="p-4 lg:w-1/2 md:w-full">
          <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{ lead.first_name }} {{ lead.last_name }}</h2>
              <p class="leading-relaxed text-base">{{ lead.description }}</p>
              <a href="{% url 'leads:assign' lead.id %}" class="mt-3 text-indigo-500 inline-flex items-center">Assign an agent
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        
        </div>

        {% endfor %}

      </div>
    {% endif %}
  </div>
</section>



{% endblock content %}

leads/templates/leads/lead_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="bg-grey-light p-3 rounded font-sans w-full m-4">
  <ol class="list-reset flex text-grey-dark">
    <li><a href="{% url 'landing-page' %}" class="text-blue font-bold">Home</a></li>
    <li><span class="mx-2">/</span></li>
    <li><a href="{% url 'leads:list' %}" class="text-blue font-bold">Leads</a></li>
    <li><span class="mx-2">/</span></li>
    <li><a href="{% url 'leads:detail' lead.id %}" class="text-blue font-bold">{{ lead.first_name }}</a></li>
    <li><span class="mx-2">/</span></li>
    <li>Update</li>
  </ol>
</div>

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:detail' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
          <a href="{% url 'leads:lead-category-update' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
          <a href="{% url 'leads:update' lead.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
        </div>

        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rouded-md" type="submit">Update</button>
        </form>

        <div class="py-5 border-t border-gray-200 mt-5">
            <button class="w-full text-white bg-red-500 hover:bg-red-600 px-3 py-1 rouded-md">
              <a class="w-full" href="{% url 'leads:delete' lead.id %}">Delete</a>
            
            </button>
        </div>
        
        
      </div>
    </div>
  </div>
</section>

{% endblock content %}