agents/urls.py
from django.urls import path

from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name="agents"

urlpatterns = [
    path('', AgentListView.as_view(), name='list'),
    path('<int:pk>', AgentDetailView.as_view(), name='detail'),
    path('create', AgentCreateView.as_view(), name='create'),
    path('<int:pk>/update', AgentUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', AgentDeleteView.as_view(), name='delete'),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignupView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    # Reset password
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(), name='reset_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name',
        )

agents/views.py
import random
from django.core.mail import send_mail
from django.shortcuts import render, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .mixins import OrganisorAndLoginRequiredMixin
from .forms import AgentModelForm

from leads.models import Agent

# Create your views here.

class AgentListView(OrganisorAndLoginRequiredMixin, ListView):
    template_name = "agents/agent_list.html"
    
    def get_queryset(self):
        request_user_organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation = request_user_organisation)

class AgentCreateView(OrganisorAndLoginRequiredMixin, CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:list")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organisor = False
        user.set_password(f"{random.randint(0,1000000)}")
        user.save()
        Agent.objects.create(
            user=user,
            organisation = self.request.user.userprofile
        )
        send_mail(subject="You are invited to be an agent.",
        message="You were added as an agent on DJCRM. Please come login to start working.",
        from_email="test@test.com", 
        recipient_list=[user.email])
        return super(AgentCreateView, self).form_valid(form)

class AgentDetailView(OrganisorAndLoginRequiredMixin, DetailView):
    template_name = "agents/agent_detail.html"
    context_object_name = "agent"
    
    def get_queryset(self):
        request_user_organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation = request_user_organisation)

class AgentUpdateView(OrganisorAndLoginRequiredMixin, UpdateView):
    template_name = "agents/agent_update.html"
    form_class = AgentModelForm

    def get_queryset(self):
        request_user_organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation = request_user_organisation)

    def get_success_url(self):
        return reverse("agents:list")

class AgentDeleteView(OrganisorAndLoginRequiredMixin, DeleteView):
    template_name = "agents/agent_delete.html" # <- Template view
    
    def get_queryset(self):
        request_user_organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation = request_user_organisation)
    
    def get_success_url(self):
        return reverse("agents:list")

agents/templates/agents/agent_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <h2 class="text-2xl text-gray-800">Create agent</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rouded-md" type="submit">Create</button>
    </form>
    <div class="py-5 border-t border-gray-200 mt-5">
        <a class="hover:text-blue-500" href="{% url 'agents:list' %}">Go back to agents</a>
    </div>
</div>

{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <h2>Are you sure you want to delete this agent?</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="w-full text-white bg-red-500 hover:bg-red-600 px-3 py-1 rouded-md" type="submit">Delete</button>
    </form>
    <div class="py-5 border-t border-gray-200 mt-5">
        <a class="hover:text-blue-500" href="{% url 'agents:update' agent.pk %}">Go back</a>
    </div>

</div>
{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %}

{% block content %}

<div class="bg-grey-light p-3 rounded font-sans w-full m-4">
  <ol class="list-reset flex text-grey-dark">
    <li><a href="{% url 'landing-page' %}" class="text-blue font-bold">Home</a></li>
    <li><span class="mx-2">/</span></li>
    <li><a href="{% url 'agents:list' %}" class="text-blue font-bold">Agents</a></li>
    <li><span class="mx-2">/</span></li>
    <li>{{ agent.user.username }}</li>
  </ol>
</div>

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.username}} </h1>
        <div class="flex mb-4">
          <a href="{% url 'agents:detail' agent.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Details</a>
          <a href="{% url 'agents:update' agent.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Full name</span>
          <span class="ml-auto text-gray-900">{{ agent.user.first_name }} {{agent.user.last_name}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Username</span>
          <span class="ml-auto text-gray-900">{{ agent.user.username }}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">E-mail</span>
          <span class="ml-auto text-gray-900">{{ agent.user.email }}</span>
        </div>
        
        
      </div>
    </div>
  </div>
</section>

{% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content %}

<div class="bg-grey-light p-3 rounded font-sans w-full m-4">
  <ol class="list-reset flex text-grey-dark">
    <li><a href="{% url 'landing-page' %}" class="text-blue font-bold">Home</a></li>
    <li><span class="mx-2">/</span></li>
    <li>Agents</li>
  </ol>
</div>

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
            <h1 class="text-4xl text-gray-800">Agents</h1>
        </div>
        <div>
            <a href="{% url 'agents:create' %}" class="text-gray-500 hover:text-blue-500">Create new agent</a>
        </div>
    </div>

    <div class="flex flex-wrap w-full">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Username</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"># Leads</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">E-mail</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Actions</th>
          </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
          <tr>
            <td class="px-4 py-3">{{ object.user.username }}</td>
            <td class="px-4 py-3">{{ object.leads.count }}</td>
            <td class="px-4 py-3">{{ object.user.email }}</td>
            <td class="px-4 py-3"><a href="{% url 'agents:detail' object.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">Edit</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>

    </div>
  </div>
</section>



{% endblock content %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="bg-grey-light p-3 rounded font-sans w-full m-4">
  <ol class="list-reset flex text-grey-dark">
    <li><a href="{% url 'landing-page' %}" class="text-blue font-bold">Home</a></li>
    <li><span class="mx-2">/</span></li>
    <li><a href="{% url 'agents:list' %}" class="text-blue font-bold">Agents</a></li>
    <li><span class="mx-2">/</span></li>
    <li><a href="{% url 'agents:detail' agent.id %}" class="text-blue font-bold">{{ agent.user.username }}</a></li>
    <li><span class="mx-2">/</span></li>
    <li>Update</li>
  </ol>
</div>

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.username}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'agents:detail' agent.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
          <a href="{% url 'agents:update' agent.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
        </div>

        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rouded-md" type="submit">Update</button>
        </form>

        <div class="py-5 border-t border-gray-200 mt-5">
            <button class="w-full text-white bg-red-500 hover:bg-red-600 px-3 py-1 rouded-md">
              <a class="w-full" href="{% url 'agents:delete' agent.id %}">Delete</a>
            
            </button>
        </div>
        
      </div>
    </div>
  </div>
</section>

{% endblock content %}