crm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignupView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    # Reset password
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(), name='reset_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path

from .views import LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, AssignAgentView
from .views import CategoryListView, CategoryDetailView, LeadCategoryUpdateView

app_name="leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='list'),
    path('create', LeadCreateView.as_view(), name='create'),
    path('<int:pk>', LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/update', LeadUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/assign', AssignAgentView.as_view(), name='assign'),

    path('categories', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>', CategoryDetailView.as_view(), name='category-detail'),

    path('<int:pk>/category', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRM Django App</title>
    <script src="{% static 'js/main.js' %}"></script>
    <link href="{% static 'css/styles.css' %}" />
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <div class="max-w-7xl mx-auto">
        {% include "navbar.html" %}
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/landing.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="{% static 'images/dashboard.svg' %}">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            CRM built with Django
        </h1>
        <p class="mb-8 leading-relaxed">
            This CRM helps you manage your leads.
        </p>
        <div class="flex justify-center">
          <a href="{% url 'login' %}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
            Login to get started
          </a>
        </div>
      </div>
    </div>
</section>
{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">CRM with Django</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      {% if request.user.is_authenticated %}
        {% if request.user.is_organisor %}
          <a href="{% url 'agents:list' %}" class="mr-5 hover:text-gray-900">Agents</a>
        {% endif %}
      <a href="{% url 'leads:list' %}" class="mr-5 hover:text-gray-900">Leads</a>
        <a href="{% url 'logout' %}" class="mr-5 hover:text-gray-900">Logout</a>
      {% else %}
        <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Sign up</a>
      {% endif %}
    </nav>
    {% if request.user.is_authenticated %}
    Agent: {{ request.user.username }}
    {% else %}
    <button class="inline-flex items-center bg-indigo-500 border-0 py-1 px-3 focus:outline-none hover:bg-indigo-600 text-white rounded text-base mt-4 md:mt-0">
      <a href="{% url 'login'  %}">Log in</a>
      
    </button>
    {% endif %}
  </div>
</header>